{
  imports = [../../common/features/haruna.nix];

  xdg.mimeApps.defaultApplications = {
    # keep-sorted start
    "application/x-matroska" = "org.kde.haruna.desktop";
    "audio/aac" = "org.kde.haruna.desktop";
    "audio/flac" = "org.kde.haruna.desktop";
    "audio/mp4" = "org.kde.haruna.desktop";
    "audio/mpeg" = "org.kde.haruna.desktop";
    "audio/ogg" = "org.kde.haruna.desktop";
    "audio/vnd.wave" = "org.kde.haruna.desktop";
    "audio/webm" = "org.kde.haruna.desktop";
    "audio/x-aiff" = "org.kde.haruna.desktop";
    "audio/x-flac+ogg" = "org.kde.haruna.desktop";
    "audio/x-m4b" = "org.kde.haruna.desktop";
    "audio/x-matroska" = "org.kde.haruna.desktop";
    "audio/x-mp3" = "org.kde.haruna.desktop";
    "audio/x-ms-wma" = "org.kde.haruna.desktop";
    "audio/x-opus+ogg" = "org.kde.haruna.desktop";
    "audio/x-vorbis+ogg" = "org.kde.haruna.desktop";
    "audio/x-wav" = "org.kde.haruna.desktop";
    "video/3gp" = "org.kde.haruna.desktop";
    "video/3gpp" = "org.kde.haruna.desktop";
    "video/3gpp2" = "org.kde.haruna.desktop";
    "video/avi" = "org.kde.haruna.desktop";
    "video/divx" = "org.kde.haruna.desktop";
    "video/dv" = "org.kde.haruna.desktop";
    "video/fli" = "org.kde.haruna.desktop";
    "video/flv" = "org.kde.haruna.desktop";
    "video/mp2t" = "org.kde.haruna.desktop";
    "video/mp4" = "org.kde.haruna.desktop";
    "video/mp4v-es" = "org.kde.haruna.desktop";
    "video/mpeg" = "org.kde.haruna.desktop";
    "video/msvideo" = "org.kde.haruna.desktop";
    "video/ogg" = "org.kde.haruna.desktop";
    "video/quicktime" = "org.kde.haruna.desktop";
    "video/vnd.divx" = "org.kde.haruna.desktop";
    "video/vnd.mpegurl" = "org.kde.haruna.desktop";
    "video/vnd.rn-realvideo" = "org.kde.haruna.desktop";
    "video/webm" = "org.kde.haruna.desktop";
    "video/x-avi" = "org.kde.haruna.desktop";
    "video/x-flv" = "org.kde.haruna.desktop";
    "video/x-m4v" = "org.kde.haruna.desktop";
    "video/x-matroska" = "org.kde.haruna.desktop";
    "video/x-mpeg2" = "org.kde.haruna.desktop";
    "video/x-ms-asf" = "org.kde.haruna.desktop";
    "video/x-ms-wmv" = "org.kde.haruna.desktop";
    "video/x-ms-wmx" = "org.kde.haruna.desktop";
    "video/x-msvideo" = "org.kde.haruna.desktop";
    "video/x-ogm" = "org.kde.haruna.desktop";
    "video/x-ogm+ogg" = "org.kde.haruna.desktop";
    "video/x-theora" = "org.kde.haruna.desktop";
    "video/x-theora+ogg" = "org.kde.haruna.desktop";
    # keep-sorted end
  };
}
