{
  imports = [
    # keep-sorted start
    ../../../../common/features/atlauncher.nix
    ../../../../common/features/ayugram-desktop.nix
    ../../../../common/features/baloo.nix
    ../../../../common/features/binaryninja.nix
    ../../../../common/features/corefonts.nix
    ../../../../common/features/croc.nix
    ../../../../common/features/filelight.nix
    ../../../../common/features/flatpak.nix
    ../../../../common/features/fontconfig.nix
    ../../../../common/features/freesmlauncher.nix
    ../../../../common/features/gpg-agent-pinentry-qt.nix
    ../../../../common/features/handbrake.nix
    ../../../../common/features/heroic.nix
    ../../../../common/features/hydra-check.nix
    ../../../../common/features/kactivitymanagerd.nix
    ../../../../common/features/kcalc.nix
    ../../../../common/features/kdenlive.nix
    ../../../../common/features/kdialog.nix
    ../../../../common/features/kleopatra.nix
    ../../../../common/features/krdc.nix
    ../../../../common/features/ktorrent.nix
    ../../../../common/features/mcpelauncher-ui-qt.nix
    ../../../../common/features/meslo-nerd-font.nix
    ../../../../common/features/mousai.nix
    ../../../../common/features/nix-alien.nix
    ../../../../common/features/obs-studio.nix
    ../../../../common/features/onlyoffice.nix
    ../../../../common/features/pear-desktop.nix
    ../../../../common/features/podman-compose.nix
    ../../../../common/features/qtscrcpy.nix
    ../../../../common/features/sidequest.nix
    ../../../../common/features/sober.nix
    ../../../../common/features/super-productivity.nix
    ../../../../common/features/syncthing-tray.nix
    ../../../../common/features/thermalmonitor.nix
    ../../../../common/features/tor-browser.nix
    ../../../../common/features/trayscale.nix
    ../../../../common/features/umu-launcher.nix
    ../../../../common/features/vista-fonts.nix
    ../../../../common/features/wayvr.nix
    ../../../../common/features/wireplumber-oneplus-buds-pro-3.nix
    ../../../../common/features/xdg-mime-apps.nix
    ../../../../common/features/yaas.nix
    ../../../../common/features/yt-dlp.nix
    # keep-sorted end

    # keep-sorted start
    ../../../features/a2s.nix
    ../../../features/antigravity-cli.nix
    ../../../features/ark.nix
    ../../../features/attic.nix
    ../../../features/atuin.nix
    ../../../features/bambu-studio.nix
    ../../../features/blender.nix
    ../../../features/bruno.nix
    ../../../features/bs-manager.nix
    ../../../features/chromium.nix
    ../../../features/cinny.nix
    ../../../features/codex.nix
    ../../../features/distrobox.nix
    ../../../features/dolphin.nix
    ../../../features/email.nix
    ../../../features/git-hardware-signing.nix
    ../../../features/gpg.nix
    ../../../features/half-life-asset-manager.nix
    ../../../features/haruna.nix
    ../../../features/imhex.nix
    ../../../features/kdeconnect.nix
    ../../../features/keepassxc.nix
    ../../../features/konsole.nix
    ../../../features/kwallet-keepassxc.nix
    ../../../features/lazygit.nix
    ../../../features/lazyvim.nix
    ../../../features/librewolf.nix
    ../../../features/mangohud.nix
    ../../../features/mcp.nix
    ../../../features/niks3.nix
    ../../../features/nix.nix
    ../../../features/plasma.nix
    ../../../features/spectacle.nix
    ../../../features/ssh-agent.nix
    ../../../features/ssh-fido2.nix
    ../../../features/steam.nix
    ../../../features/syncthing.nix
    ../../../features/thunderbird.nix
    ../../../features/virt-manager.nix
    ../../../features/vscodium.nix
    ../../../features/wakatime.nix
    ../../../features/wl-clipboard.nix
    # keep-sorted end

    # keep-sorted start
    ./ghidra.nix
    ./kdeconnect.nix
    ./librewolf.nix
    ./looking-glass.nix
    ./openrazer.nix
    ./plasma.nix
    ./sops.nix
    ./stylix.nix
    ./syncthing.nix
    ./thermalmonitor.nix
    ./vscodium.nix
    # keep-sorted end
  ];
}
