on:
  push:
    branches:
      - main

    paths:
      - .github/workflows/sync-atelier-config.yaml

      - atelier.toml.in
      - flake.nix

  workflow_dispatch:

jobs:
  sync-atelier-config:
    concurrency:
      # one sync per branch; newer runs cancel older runs
      group: ${{ github.workflow }}-${{ github.ref }}

      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.ATELIER_SYNC_PAT }}

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          extra_nix_config: accept-flake-config = true

      - id: collect-flake-config
        run: |
          {
            printf 'extra-substituters=%s\n' "$(nix eval --json --file flake.nix --apply 'flake: flake.nixConfig.extra-substituters' | jq --compact-output)"
            printf 'extra-trusted-public-keys=%s\n' "$(nix eval --json --file flake.nix --apply 'flake: flake.nixConfig.extra-trusted-public-keys' | jq --compact-output)"

            printf 'systems=%s\n' "$(nix eval --json .#systems | jq --compact-output)"
          } >> $GITHUB_OUTPUT

      - env:
          SUBSTITUTERS: ${{ steps.collect-flake-config.outputs['extra-substituters'] }}
          TRUSTED_PUBLIC_KEYS: ${{ steps.collect-flake-config.outputs['extra-trusted-public-keys'] }}

          SYSTEMS: ${{ steps.collect-flake-config.outputs.systems }}
        run: |
          sed \
            --expression '1i# auto-generated by `.github/workflows/sync-atelier-config.yaml`; do not edit' \
            --expression "s|@SUBSTITUTERS@|$SUBSTITUTERS|g" \
            --expression "s|@TRUSTED_PUBLIC_KEYS@|$TRUSTED_PUBLIC_KEYS|g" \
            --expression "s|@SYSTEMS@|$SYSTEMS|g" \
            atelier.toml.in > atelier.toml

      - run: |
          git add atelier.toml

          if git diff --quiet --cached -- atelier.toml; then
            exit 0
          fi

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git commit --message 'chore(atelier): sync config'

          git push
